apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveproject
  labels:
    app: nginx-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: devopsbyrushi/myapplication:v1
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: my-service-liveproject
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
    - nodePort: 31111
      port: 80
      targetPort: 80
